<script setup>
import { computed } from 'vue';
import {
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Barcode,
  Bell,
  ChartColumn,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  ClipboardList,
  Download,
  ExternalLink,
  Eye,
  FileX,
  FilterX,
  Flower,
  Grid3x3,
  Info,
  LayoutGrid,
  Leaf,
  List,
  ListTodo,
  Map,
  MapPin,
  Menu,
  Moon,
  MoreHorizontal,
  Mountain,
  Package,
  PawPrint,
  Pencil,
  Plus,
  ReceiptText,
  RefreshCw,
  Rows3,
  Search,
  Settings,
  Shapes,
  ShieldCheck,
  ShoppingBasket,
  Sprout,
  Square,
  Sun,
  Tractor,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trees,
  UserRound,
  Users,
  Wrench,
  X,
} from '@lucide/vue';

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  size: {
    type: [Number, String],
    default: 20,
  },
  strokeWidth: {
    type: [Number, String],
    default: 1.8,
  },
});

const icons = {
  add: Plus,
  agriculture: Tractor,
  arrow_downward: ArrowDown,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  arrow_upward: ArrowUp,
  assignment_late: FileX,
  barcode: Barcode,
  bell: Bell,
  border_all: Grid3x3,
  build: Wrench,
  category: Shapes,
  check_box_outline_blank: Square,
  check_circle: CircleCheck,
  check_square: CheckSquare,
  checklist: ClipboardList,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  dark_mode: Moon,
  dehaze: Rows3,
  delete: Trash2,
  download: Download,
  eco: Leaf,
  edit: Pencil,
  error: CircleAlert,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  external_link: ExternalLink,
  eye: Eye,
  filter_alt_off: FilterX,
  format_list_bulleted: List,
  grid_on: LayoutGrid,
  grid_view: LayoutGrid,
  groups: Users,
  import_export: ArrowDownUp,
  info: Info,
  insert_chart: ChartColumn,
  inventory_2: Package,
  landscape: Mountain,
  light_mode: Sun,
  location_on: MapPin,
  map: Map,
  menu: Menu,
  more_horiz: MoreHorizontal,
  notifications: Bell,
  open_in_new: ExternalLink,
  park: Trees,
  pending_actions: ListTodo,
  person: UserRound,
  pets: PawPrint,
  pin_drop: MapPin,
  potted_plant: Sprout,
  refresh: RefreshCw,
  refresh_cw: RefreshCw,
  request_quote: ReceiptText,
  search: Search,
  settings: Settings,
  shield_with_heart: ShieldCheck,
  shopping_basket: ShoppingBasket,
  spa: Flower,
  stop: Square,
  straight: ArrowUp,
  trending_up: TrendingUp,
  triangle_alert: TriangleAlert,
  unarchive: Archive,
  visibility: Eye,
  warning: TriangleAlert,
  wrench: Wrench,
};

const icon = computed(() => icons[props.name] || CircleAlert);
</script>

<template>
  <component :is="icon" :size="size" :stroke-width="strokeWidth" v-bind="$attrs" />
</template>
